var index =
[
    [ "Introduction", "index.html#intro_sec", null ],
    [ "What's New", "whatsnew.html", null ],
    [ "Change log", "changelog.html", null ],
    [ "Installation", "installation.html", [
      [ "Step 1: Prerequisites", "installation.html#step1", null ],
      [ "Step 2: Getting the software", "installation.html#step2", null ],
      [ "Step 3: Compile and Install the software", "installation.html#step3", null ],
      [ "Step 4: Run QSSTV", "installation.html#step4", null ],
      [ "Step 5 (only for debug): Debug compile", "installation.html#step5", null ]
    ] ],
    [ "Getting Started", "gettingstarted.html", null ],
    [ "Configuration", "config.html", null ],
    [ "Volume Settings", "volume.html", null ],
    [ "SSTV Calibration", "calib.html", null ],
    [ "Statusbar", "statusbar.html", null ],
    [ "Image Viewer", "imagepopup.html", null ],
    [ "Receive SSTV Window", "_r_x_s_s_t_v.html", null ],
    [ "Transmit SSTV Window", "_t_x_s_s_t_v.html", null ],
    [ "Receive DRM Window", "_r_x_d_r_m.html", null ],
    [ "Transmit DRM Window", "_t_x_d_r_m.html", null ],
    [ "Mode Settings for DRM", "drmmodes.html", null ],
    [ "Sending FIX in DRM", "fixdrm.html", null ],
    [ "Spectrum and Waterfall Display", "spectrumwf.html", null ],
    [ "Gallery", "gallery.html", null ],
    [ "Editor version 9.2 and 9.3", "editor93.html", null ],
    [ "Editor version 9.4", "editor94.html", null ],
    [ "Macro Text", "macros.html", null ],
    [ "Repeater", "repeater.html", null ],
    [ "External Programs", "externalprog.html", null ],
    [ "To Do", "todo1.html", null ],
    [ "Credits", "credits.html", null ],
    [ "Copying", "_copying.html", null ]
];